name: the_flashcard
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  audioplayers: 0.14.1
  auto_size_text: 2.1.0
  cached_network_image: 2.4.1
  charts_flutter: 0.9.0
  chewie: 0.9.10
  cupertino_icons: 0.1.2
  ddi: 0.1.1
  dio: 3.0.10
  equatable: 1.1.1
  file_picker: 1.5.0+2
  flare_flutter: 2.0.1
  flip: 1.0.0
  flutter_animation_progress_bar: 1.0.0
  flutter_bloc: 6.1.1
  flutter_cache_manager: 2.0.0
  flutter_circular_chart: 0.1.0
  flutter_custom_clippers: 1.1.0
  flutter_flip_view: 1.0.3
  flutter_slidable: 0.5.4
  flutter_sound: 2.1.1
  flutter_staggered_grid_view: 0.3.0
  flutter_svg: 0.17.3+1
  flutter_swiper: 1.1.6
  flutter_vector_icons: 0.1.0
  flutter_youtube: 2.0.0
  image_picker: 0.6.3+4
  intl: 0.16.1
  open_iconic_flutter: 0.3.0
  outline_material_icons: 0.1.0
  path_provider: 1.6.24
  photo_view: 0.9.2
  pull_to_refresh: 1.5.8
  rich_text_controller: 1.1.0
  shared_preferences: 0.5.6+3
  shimmer: 1.1.1
  tf_core:
    path: tf_core
  url_launcher: 5.4.2
  video_player: 0.10.8+1
  wave_progress_bars: 0.1.0
  youtube_player_flutter: 6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/backgrounds/
    - assets/icons/
    - assets/icons/flags/
    - assets/verify/shutterstock1205161000@3x.png
    - assets/audios/
    - assets/flares/
  fonts:
    - family: HarmoniaSansProCyr
      fonts:
        - asset: assets/fonts/new_fonts/Harmonia-Light.ttf
          weight: 900

        - asset: assets/fonts/new_fonts/Harmonia-Bold.ttf
          weight: 700

        - asset: assets/fonts/new_fonts/Harmonia-SemiBold.ttf
          weight: 600

        - asset: assets/fonts/new_fonts/Harmonia-Regular.ttf
          weight: 400

        - asset: assets/fonts/HarmoniaSansProCyr-Italic.ttf
          style: italic

    - family: DoulosSIL
      fonts:
        - asset: assets/fonts/DoulosSIL-R.ttf

    - family: Harmonia
      fonts:
        - asset: assets/fonts/harmonia/Harmonia-Regular.ttf

    - family: Round
      fonts:
        - asset: assets/fonts/round/iCielVAGRoundedNext-Regular.ttf
    - family: Gothic
      fonts:
        - asset: assets/fonts/gothic/UTM-Alter-Gothic.ttf

    - family: Graceland
      fonts:
        - asset: assets/fonts/graceland/UTM-A&S-Graceland.ttf

    - family: Tiempos
      fonts:
        - asset: assets/fonts/new_fonts/TiemposHeadline-Medium.ttf
          weight: 600
        - asset: assets/fonts/new_fonts/TiemposHeadline-Regular.ttf
          weight: 400

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
