name: tf_core
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: 3.0.10
  hive: 1.4.4
  hive_flutter: 0.3.1
  ansicolor: 1.0.5
  http: 0.12.2
  path_provider: 1.6.5
  intl: 0.16.1
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
